---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberrootmusic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cyberrootmusic
  template:
    metadata:
      labels:
        app: cyberrootmusic
    spec:
      containers:
        - name: cyberrootmusic
          image: "ghcr.io/nekko-lab/cyberrootmusic-vol2:0f996ab05ca2d2b0bbbebfc611433f0de6cbe901"
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "250m"
