---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberrootmusic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cyberrootmusic
  template:
    metadata:
      labels:
        app: cyberrootmusic
    spec:
      containers:
        - name: cyberrootmusic
          image: "ghcr.io/nekko-lab/cyberrootmusic-vol2:29403d5e48ffad6afd77ecb6fadc14214a926cc7"
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "250m"
