---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fire
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fire
  template:
    metadata:
      labels:
        app: fire
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113" # Exporterが公開するポート
        prometheus.io/path: "/metrics"
    spec:
      volumes:
        - name: nginx-logs
          emptyDir: {}
      containers:
        - name: fire
          image: "ghcr.io/nekko-lab/tsudanuma25-hp:8f80dd84df0bf39e93ca7e3c958a7742a21de995"
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: nginx-logs
              mountPath: /var/log/nginx
        - name: nginx-exporter
          image: "nginx/nginx-prometheus-exporter:1.5.1"
          args:
            - -nginx.scrape-uri=http://localhost:80/metrics
          ports:
            - containerPort: 9113
              name: metrics
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
